WELCOME_MESSAGE = "Добро пожаловать"
CREATE_MESSAGE = "Вы создаете комнату"
JOIN_MESSAGE = "Вы подключаетесь к комнате, нужно написать пароль"
ROOM_CREATED = "Комната создана %id%"
ROOM_IS_NOT_FOUND = "Комната не найдена"
ROOM_IS_FULL = "Комната заполнена"
JOIN_SELLER = "Вы присоеденились в комнату %id% как продавец"
JOIN_BUYER = "Вы присоеденились в комнату %id% как покупатель"

CREATE_BUTTON_TEXT = "Созадать комнату"
JOIN_BUTTON_TEXT = "Войти в комнату"
BUYER_BUTTON_TEXT = "Продавец"
SELLER_BUTTON_TEXT = "Покупатель"

BOT_TOKEN = "6923274920:AAHBbI0Fnet1SqvcHS9ptdB3NNe8F9Z1oPE"
